### ISSUE TITLE
Failure when secret does not exist in origin but present in origin metadata

### ISSUE THREAD

**Issue by saipranav** [ExpediaGroup/vsync#47]
There is a Seg Fault
```
goroutine 126 [running]:
github.com/ExpediaGroup/vsync/syncer.FetchAndSave(0xba2bc0, 0xc0001c3e00, 0xc000027430, 0x1f, 0xc0000f5050, 0xc0001988a0, 0xc0000840a0, 0xc0000fa7c0, 0x2, 0x2, ...)
	/home/runner/work/vsync/vsync/syncer/destination.go:67 +0x465
created by github.com/ExpediaGroup/vsync/cmd.destinationSync
	/home/runner/work/vsync/vsync/cmd/destination.go:492 +0x154f
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x850925]
```

The scenario is when we have origin metadata for a secret that is deleted in origin side
     but vsync origin is yet to pickup in preparing and storing its metadata

Destination vsync needs to pull up the secret and it throws it does not exist. The errors are not surface even worse is the channels are not closed completely and exits with error code 2

This issue would have been caught beforehand if we are testing the delayed sync cycles between origin and destination unlike in our testing both cycles happen so quickly and we missed this scenario.

**Comment by saipranav** [comment]
For testing this scenario ( yet to do ):
1. Run bootstrap
2. Start vsync origin and destination
3. Stop origin, so that metadata stays unchanged
4. Delete a secret in origin 
5. Wait for destination cycle to seg vault
